export interface DealInput { ticket:string; positionId?:string|null; symbol:string; type:number; direction:number; volume:number; price:number; profit:number; commission:number|null; swap:number|null; fee:number|null; time:Date|string; }
export interface PositionInput { ticket:string; symbol:string; type:number; volume:number; priceOpen:number; sl?:number|null; tp?:number|null; priceCurrent:number; profit:number; swap?:number|null; comment?:string|null; magic?:number|null; openTime:Date|string; }
export interface SnapshotInput { balance:number; equity:number; createdAt:Date|string; }
export interface ClosedPosition { positionId:string; symbol:string; volume:number; openTime:Date; closeTime:Date; netProfit:number; rawProfit:number; commission:number; swap:number; }
export interface MonthlyStat { month:string; lots:number; trades:number; winRate:number|null; profit:number; balance:number|null; }
export interface EquityPoint { t:number; balance:number; equity:number; }
export interface Metrics { balance:number; equity:number; growthPct:number; maxDrawdownPct:number; currentDrawdownPct:number; profitFactor:number|null; winRatePct:number|null; totalTrades:number; totalLots:number; netProfit:number; monthly:MonthlyStat[]; equityCurve:EquityPoint[]; startBalance:number; startEquity:number; netCashFlow:number; }
const asDate=(d:Date|string):Date=>d instanceof Date?d:new Date(d);
export function netProfitOf(d:DealInput):number{return d.profit+(d.commission??0)+(d.swap??0)+(d.fee??0)}
export function toUsd(amount:number,cent:boolean):number{return cent?amount/100:amount}
export function toStdLots(lots:number,cent:boolean):number{return cent?lots/100:lots}
export function isCashFlowDeal(d:DealInput):boolean{return d.type===2||d.type===3}
export function cashFlowUpTo(deals:DealInput[],t:number):number{let sum=0;for(const d of deals)if(isCashFlowDeal(d)&&asDate(d.time).getTime()<=t)sum+=d.profit;return sum}
function isPositionDeal(d:DealInput):d is DealInput&{positionId:string}{return !!d.positionId&&d.positionId!=="0"&&d.type!==2&&d.type!==3}
export function buildClosedPositions(deals:DealInput[]):ClosedPosition[]{const by=new Map<string,DealInput[]>();for(const d of deals){if(!isPositionDeal(d))continue;const a=by.get(d.positionId)??[];a.push(d);by.set(d.positionId,a)}const out:ClosedPosition[]=[];for(const[positionId,a]of by){if(!a.some(d=>d.direction!==0))continue;let net=0,raw=0,commission=0,swap=0,volume=0;let open:Date|null=null,close:Date|null=null,symbol="";for(const d of a){net+=netProfitOf(d);raw+=d.profit;commission+=d.commission??0;swap+=d.swap??0;const t=asDate(d.time);if(!open||t<open)open=t;if(!close||t>close)close=t;if(d.volume>volume){volume=d.volume;symbol=d.symbol}}if(open&&close)out.push({positionId,symbol,volume,openTime:open,closeTime:close,netProfit:net,rawProfit:raw,commission,swap})}return out.sort((a,b)=>a.closeTime.getTime()-b.closeTime.getTime())}
const monthKeyOf=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;
export function monthKey(d:Date|string):string{return monthKeyOf(asDate(d))}
export function computeMetrics(deals:DealInput[],positions:PositionInput[],snapshots:SnapshotInput[],opts:{cent?:boolean}={}):Metrics{const closed=buildClosedPositions(deals);const snaps=[...snapshots].map(s=>({balance:s.balance,equity:s.equity,t:asDate(s.createdAt).getTime()})).sort((a,b)=>a.t-b.t);const startBalance=snaps[0]?.balance??0,startEquity=snaps[0]?.equity??startBalance,last=snaps.at(-1),balance=last?.balance??startBalance,equity=last?.equity??startBalance;const cfBefore=snaps.length?cashFlowUpTo(deals,snaps[0].t):0,cfAll=cashFlowUpTo(deals,last?.t??Infinity),adjStart=startEquity-cfBefore,adjEnd=equity-cfAll;let peak=-Infinity,maxDD=0;for(const s of snaps){const adj=s.equity-cashFlowUpTo(deals,s.t);peak=Math.max(peak,adj);if(peak>0)maxDD=Math.max(maxDD,(peak-adj)/peak*100)}const currentDrawdownPct=peak>0?(peak-adjEnd)/peak*100:0;const growthPct=adjStart!==0?(adjEnd-adjStart)/Math.abs(adjStart)*100:0;const totalTrades=closed.length,wins=closed.filter(c=>c.netProfit>0).length,grossProfit=closed.filter(c=>c.netProfit>0).reduce((s,c)=>s+c.netProfit,0),grossLoss=Math.abs(closed.filter(c=>c.netProfit<0).reduce((s,c)=>s+c.netProfit,0)),winRatePct=totalTrades?(wins/totalTrades)*100:null,profitFactor=grossLoss===0?(grossProfit>0?Infinity:grossProfit===0?null:0):grossProfit/grossLoss,netProfit=closed.reduce((s,c)=>s+c.netProfit,0),totalLots=deals.filter(d=>d.type===0||d.type===1).reduce((s,d)=>s+d.volume,0)/2;const monthSet=new Set<string>();for(const d of deals)monthSet.add(monthKeyOf(asDate(d.time)));for(const c of closed)monthSet.add(monthKeyOf(c.closeTime));const monthly=[...monthSet].sort().map(month=>{const cs=closed.filter(c=>monthKeyOf(c.closeTime)===month),ds=deals.filter(d=>monthKeyOf(asDate(d.time))===month&&(d.type===0||d.type===1)),end=new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),1).getTime(),start=new Date(Number(month.slice(0,4)),Number(month.slice(5,7))-1,1).getTime(),snap=[...snaps].filter(s=>s.t>=start&&s.t<end).at(-1);return{month,lots:ds.reduce((s,d)=>s+d.volume,0)/2,trades:cs.length,winRate:cs.length?cs.filter(c=>c.netProfit>0).length/cs.length*100:null,profit:cs.reduce((s,c)=>s+c.netProfit,0),balance:snap?.balance??null}});return{balance,equity,growthPct,maxDrawdownPct:maxDD,currentDrawdownPct,profitFactor,winRatePct,totalTrades,totalLots,netProfit,monthly,equityCurve:snaps.map(s=>({t:s.t,balance:s.balance,equity:s.equity})),startBalance,startEquity,netCashFlow:cfAll}}
export interface GrowthDDPoint{t:number;growthPct:number;ddPct:number}
export function growthDrawdownSeries(snapshots:SnapshotInput[],deals:DealInput[]=[]):GrowthDDPoint[]{const snaps=[...snapshots].map(s=>({equity:s.equity,t:asDate(s.createdAt).getTime()})).sort((a,b)=>a.t-b.t);if(!snaps.length)return[];const first=snaps[0].equity-cashFlowUpTo(deals,snaps[0].t);let peak=-Infinity;return snaps.map(s=>{const adj=s.equity-cashFlowUpTo(deals,s.t);peak=Math.max(peak,adj);return{t:s.t,growthPct:first?(adj-first)/Math.abs(first)*100:0,ddPct:peak>0?-(peak-adj)/peak*100:0}})}
export interface SymbolStat{symbol:string;lots:number;volumeShare:number;wins:number;losses:number;winRate:number|null;pnl:number}
export function symbolStats(deals:DealInput[]):SymbolStat[]{const by=new Map<string,SymbolStat>();for(const c of buildClosedPositions(deals)){const s=by.get(c.symbol)??{symbol:c.symbol,lots:0,volumeShare:0,wins:0,losses:0,winRate:null,pnl:0};s.lots+=c.volume;s.pnl+=c.netProfit;if(c.netProfit>0)s.wins++;else if(c.netProfit<0)s.losses++;by.set(c.symbol,s)}const out=[...by.values()],total=out.reduce((n,s)=>n+s.lots,0);for(const s of out){s.volumeShare=total?s.lots/total*100:0;const n=s.wins+s.losses;s.winRate=n?s.wins/n*100:null}return out.sort((a,b)=>b.pnl-a.pnl||b.lots-a.lots)}
export function openPositionsSummary(positions:PositionInput[],opts:{cent?:boolean}={}):{count:number;volume:number;profit:number;swap:number}{return positions.reduce((a,p)=>{a.count++;a.volume+=p.volume;a.profit+=p.profit;a.swap+=p.swap??0;return a},{count:0,volume:0,profit:0,swap:0})}
